### ISSUE TITLE
create approle secret ID with wrap-ttl

### ISSUE THREAD

**Issue by ben512** [ianunruh/hvac#106]
Looks like there is no way to create approle secret ID with wrap-ttl (create_role_secret_id)?

If yes, could you point out how it can be done?

Thanks!

**Comment by jeffwecan** [comment]
It looks like you can just pass the `wrap_ttl` parameter to the `create_role_secret_id()` method at this point: https://github.com/ianunruh/hvac/blob/master/hvac/v1/__init__.py#L951.
