### ISSUE TITLE
Vault logout

### ISSUE THREAD

**Issue by jamesdmorgan** [ianunruh/hvac#120]
Hi,

When I logout using **client.logout()** I find that the **.vault-token** file is still present in the home directory for the user that ran it.

Am I doing something wrong? Would you expect that to be cleaned up?

Many thanks

**Comment by powellc** [comment]
If you look in the logout function, removing files is not part of the behavior. The logout function simply removes any token living memory. Command line access to Vault will persist, by design.

For security, you can pass revoke_token=False to the logout function and it will remove the token's access, that way it doesn't matter if the vault-token dotfile is still present in the home directory.

**Comment by jamesdmorgan** [comment]
Hi, I had looked in the function and wondered if it was an omission

The problem I have is that we have an ansible user that uses a non-root but still privileged token. 

If anybody logs in to a machine as that user then they can instantly access vault with those privileges. I would have hoped that you would always need to auth explicitly when using the cli.

I can't revoke the token as its needed by the ansible user. 

I will lock down the user so we can mitigate this issue but keeping state on the host seems like a security issue.

I will look to remove the .vault_token in my modules that invoke hvac. Every module authorises each time so they stateless. 

Happy to have this closed

Thanks

**Comment by powellc** [comment]
That seems like a reasonable work flow, but hvac is not a tool for managing host access to vault, but rather a library for interacting with the API with python. If you need the vault_token dotfile removed after a run, you'd be better served to use a tool like Fabric, or an orchestration tool like Ansible or Chef.

**Comment by jamesdmorgan** [comment]
Yeah that's fair enough, i'll add it to my ansible modules that use hvac. Thanks

**Comment by jamesdmorgan** [comment]
As of 0.7.3 there is a **no-store** option to vault auth. Would address this issue.

https://github.com/hashicorp/vault/issues/2746

**Comment by otakup0pe** [comment]
Seems like this resolved nicely...
