### ISSUE TITLE
Cannot authenticate using auth_approle

### ISSUE THREAD

**Issue by bigmyx** [ianunruh/hvac#122]
Hi,
I am trying to authenticate with Vault using app_role backend:

```
...
>>> client = hvac.Client(url='http://localhost:8200')
>>> client.auth_approle(APP_ROLE, SECRET_ID)
>>> client.is_authenticated()
False
```

What did I miss?

**Comment by stephanh** [comment]
@bigmyx I am not sure why the code path for app role is different but you can do:

```
>>> client.token = client.auth_approle(APP_ROLE, SECRET_ID)['auth']['client_token']
>>> client.is_authenticated()
True
```

**Comment by Alan-R** [comment]
I did the same thing to get it to work. Inconsistent with the other usages.

**Comment by wolftrouble** [comment]
https://github.com/ianunruh/hvac/pull/115 was merged (thanks @Alan-R and @otakup0pe!) so this should be fixed now.
