### ISSUE TITLE
Return None for keys which don't exist

### ISSUE THREAD

**Issue by DavidWittman** [ianunruh/hvac#13]
I'm all for asking for forgiveness rather than permission, but raising an `InvalidPath` exception for every missed read seems a little excessive. Would you be opposed to returning `None` instead?

This is similar to how the `vault-ruby` client handles it. 

``` ruby
  class Logical < Request
    # Read the secret at the given path. If the secret does not exist, +nil+
    # will be returned.
    #
    # @example
    #   Vault.logical.read("secret/password") #=> #<Vault::Secret lease_id="">
    #
    # @param [String] path
    #   the path to read
    #
    # @return [Secret, nil]
    def read(path)
      json = client.get("/v1/#{path}")
      return Secret.decode(json)
    rescue HTTPError => e
      return nil if e.code == 404
      raise
    end
```
https://github.com/hashicorp/vault-ruby/blob/master/lib/vault/api/logical.rb#L16-L32

**Comment by ianunruh** [comment]
I agree, this will make using the client more friendly.

**Comment by DavidWittman** [comment]
:+1: Thanks @ianunruh!
