### ISSUE TITLE
lease should not be added to the content when using client.write()

### ISSUE THREAD

**Issue by cscetbon** [ianunruh/hvac#135]
Hey,

There is no reason the lease value goes into the content of the secret
```
>client.write('secret/test/cyril/item1', username='u1', password='p1', cont='blabla', lease='2h')
>client.read('secret/test/cyril/item1')['data']
{u'cont': u'blabla',
 u'lease': u'2h',
 u'password': u'p1',
 u'username': u'u1'}
```

It's because you use `kwargs` as the json dictionary input when you pass send it to the API

**Comment by otakup0pe** [comment]
This seems kinda related to #133 in that it is a side effect of `kwargs`...

**Comment by cscetbon** [comment]
right, same cause, different consequences

**Comment by otakup0pe** [comment]
Going to track all variants of this woe in the other issue...
