### ISSUE TITLE
Python 3.5.2 incompatibility issue

### ISSUE THREAD

**Issue by Nethika** [ianunruh/hvac#141]
With Python 3.5.2, Vault is trying to use TLSV1
It doesn't default the TLS protocol to the highest available.

ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)

Note: The PROTOCOL_TLS constant is defined in 3.5.3
Internal dependency is for urllib3 rather than Vault?
With Python 3.5.2:
>>> import ssl
>>> ssl.PROTOCOL_TLS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLS'

**Comment by otakup0pe** [comment]
What other details can you provide on your system? We are successfully using `hvac` in a bunch of tools on Python 2.7 and 3.6 on macs and linux.

**Comment by Nethika** [comment]
Sorry, I updated to to 3.6 I cannot recreate the error now.

**Comment by otakup0pe** [comment]
There is a lot of weirdness with SSL (especially on macs) and Python. Glad it's working now!
