### ISSUE TITLE
Travis failing because tox something

### ISSUE THREAD

**Issue by otakup0pe** [ianunruh/hvac#142]
Not sure what's up with this, but it seems that the non-2.x builds are failing. Might be related to travis containers being updated...

**Comment by ianwestcott** [comment]
Here's the error from my failed build in https://github.com/ianunruh/hvac/pull/140:

```
ERROR: Error creating virtualenv. Note that some special characters (e.g. ':' 
and unicode symbols) in paths are not supported by virtualenv. Error details: 
InvocationError("Failed to get version_info for python3.5: pyenv: python3.5: 
command not found\n\nThe `python3.5' command exists in these Python 
versions:\n  3.5\n  3.5.3\n\n",)
```

It sounds like Travis CI thinks Python 3.5 isn't installed? 

Going by the Travis CI docs, we may need to specify which versions of Python we want installed in the build environment: https://docs.travis-ci.com/user/languages/python/

I'll open a PR to test this theory.

**Comment by ianwestcott** [comment]
Alright, it took some experimentation, and a crash course in [defining build matrices](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix), but I have a passing setup that I think satisfies this project's needs: https://github.com/ianunruh/hvac/pull/143

Feel free to tweak that or rewrite it as needed.
