### ISSUE TITLE
Typo: Documentation for install

### ISSUE THREAD

**Issue by RAbraham** [ianunruh/hvac#152]
Hi,
The README mentions 
```bash
pip install hvac[parser]
```
which didn't work for me. What worked was adding the quotes around `hvac[parser]`

```bash
pip install "hvac[parser]"
```

**Comment by otakup0pe** [comment]
It would be really great if you could open a pull request for this! Super easy, and you can probably even do it via the web interface.

**Comment by RAbraham** [comment]
Absolutely. https://github.com/ianunruh/hvac/pull/154. Let me know if you need it done another way.
