### ISSUE TITLE
client object instantiates with a bad url

### ISSUE THREAD

**Issue by defionscode** [ianunruh/hvac#18]
With hvac 0.2.3 on OSX

Currently, passing in a bad url doesn't throw any error or exception

Doing:

`client = hvac.Client(url='http://234.244.22.2:8200', token='sometoken')`

Successfully creates the client object. I think it should probably be validated in `__init__` and throw a ConnectionError exception. 

I'll get around to submitting a PR sometime this week if you agree with me.

**Comment by ianunruh** [comment]
How would you propose to valid the URL? I'd like to avoid doing an HTTP request in `__init__` if possible.

**Comment by defionscode** [comment]
My initial idea was to make a request. If not a request then we could do smth with urlparse + regex. It's not easy without resorting to a HTTP request.

The other issue is b/c the object can be instantiated, calling something like `is_authenticated()` makes the code hang indefinitely when the object is created with a bad endpoint. 

I agree it's not pretty to do it within `__init__`, though do you think it is better for there to be no error/exception when a specified endpoint is invalid? Perhaps we could make a `is_valid_endpoint()` method (or smth along those lines).

**Comment by ianunruh** [comment]
If it is hanging indefinitely, that is an issue. Have you experienced this? requests should eventually timeout.

**Comment by ianunruh** [comment]
I'm going to go ahead and close this. Please feel free to reopen if this problem still affects you!
