### ISSUE TITLE
Document How to Turn Off SSL Verification

### ISSUE THREAD

**Issue by jeffwecan** [ianunruh/hvac#189]
Additional context in https://github.com/ianunruh/hvac/pull/139

**Comment by Brcrwilliams** [comment]
It would also be helpful to document how the verify flag can be used to verify self-signed certificates: `verify='/path/to/cert.cer'`. If you are using a self-signed certificate, this is preferable to disabling certificate verification.

**Comment by jeffwecan** [comment]
@Brcrwilliams: That should already be covered by the [existing docs](https://github.com/ianunruh/hvac#initialize-the-client) I believe. If not, please clarify what is lacking and I can get that added in as well.
