### ISSUE TITLE
Writes Sometimes Return Information

### ISSUE THREAD

**Issue by theonewolf** [ianunruh/hvac#19]
The PKI secret backend returns the public/private/CA certificates and key via a write.

The write call in HVAC appears to return `None`, and I'd like to get at its actual response to get the values back.

Example call that is currently returning `None`:

```python
#!/usr/bin/env python
# vim:set nospell:

from hvac import Client
from os import environ

if __name__ == '__main__':
    client = Client(url="https://identity-1.node:8200",
                    token=environ['VAULT_TOKEN'], verify=False)
    nodecert = client.write('pki/issue/node-soroco', common_name='identity-1.node')
    print nodecert
```

Whereas the CLI interface returns values.

**Comment by ianunruh** [comment]
Thanks for bringing this to my attention. Fixed in 6242efffa515b1d162941126ecd058b1e6ca0149

**Comment by theonewolf** [comment]
Can we get a hotfix release for this to PyPI?  Sorry for making you do work :laughing:

**Comment by ianunruh** [comment]
Done :smile:

**Comment by theonewolf** [comment]
Wish you were on the east coast.  I owe you.
