### ISSUE TITLE
Add option to skip SSL certificate verification

### ISSUE THREAD

**Issue by tdi** [ianunruh/hvac#20]
First of all thank you for your 
This option will allow to use HVAC with vault API secured with StartSSL certs.

**Comment by ianunruh** [comment]
Hello! It's not documented in the readme, but there is an option when constructing the client to disable SSL verification.

https://github.com/ianunruh/hvac/blob/master/hvac/v1/__init__.py#L6

**Comment by tdi** [comment]
Great ! Thanks

**Comment by ianunruh** [comment]
@tdi FYI, if you're trying to make your environment secure, you should tell HVAC where the CA certificate is, so it can actually verify the cert. You can do this by passing the path to the CA certificate (in PEM format) to the `verify` parameter on the constructor, like so:

```python
from hvac import Client

client = Client(url='https://vault:8200', verify='/path/to/startssl/ca-cert.pem')
```

**Comment by tdi** [comment]
Yes ! works nicely with ca-bundle.pem form StartSSL super thanks @ianunruh
