### ISSUE TITLE
Version 0.6.1 breaks auth_userpass

### ISSUE THREAD

**Issue by DGollings** [ianunruh/hvac#217]
Admittedly with an old version of Vault, 0.7.0

There's really two issues, at some point between 0.6.0 and 0.6.1 logging into the vault using auth_userpass results in the error: 'missing client token'. Although it worked in 0.6.0 but not in 0.6.0 Rolling back to 0.5.0 fixed it

Which leads me to the other issue, it appears 0.6.1 has accidentally been released as 0.6.0. Which made debugging this all a lot harder :)

In short:
old 0.6.0 = OK
new 0.6.1 = NOK
reinstalled/’new’ 0.6.0 = NOK

I've also checked the md5sums:
OK
[root@9c89d32ed7c0 site-packages]# cat /usr/lib/python2.7/site-packages/hvac/version
0.6.0
[root@9c89d32ed7c0 site-packages]# md5sum /usr/lib/python2.7/site-packages/hvac/v1/__init__.py
8e0ab8d559baade5b5ef3b2307c5088c  /usr/lib/python2.7/site-packages/hvac/v1/__init__.py

NOK
[root@861d63427d77 site-packages]# cat /usr/lib/python2.7/site-packages/hvac/version
0.6.0
[root@861d63427d77 site-packages]# md5sum /usr/lib/python2.7/site-packages/hvac/v1/__init__.py
cddac83e614c63ff270acd240d866e80  /usr/lib/python2.7/site-packages/hvac/v1/__init__.py

**Comment by jeffwecan** [comment]
Thanks for the report @DGollings! Apologies about the version mismanagement, I'll see what I can do about getting that corrected. Though I'm having trouble replicating:

```
(hvac_test) ➜  ~  $ pip  install hvac==0.6.1 --no-cache-dir
Collecting hvac==0.6.1
  Downloading https://files.pythonhosted.org/packages/d8/95/1cf607683f717e5ea5d6aea60f5df918b44355c4139714388a32ee2b7c32/hvac-0.6.1.tar.gz
Requirement already satisfied: requests>=2.7.0 in ./.venvs/hvac_test/lib/python2.7/site-packages (from hvac==0.6.1) (2.19.1)
Requirement already satisfied: idna<2.8,>=2.5 in ./.venvs/hvac_test/lib/python2.7/site-packages (from requests>=2.7.0->hvac==0.6.1) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in ./.venvs/hvac_test/lib/python2.7/site-packages (from requests>=2.7.0->hvac==0.6.1) (2018.4.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.venvs/hvac_test/lib/python2.7/site-packages (from requests>=2.7.0->hvac==0.6.1) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in ./.venvs/hvac_test/lib/python2.7/site-packages (from requests>=2.7.0->hvac==0.6.1) (1.23)
Installing collected packages: hvac
  Running setup.py install for hvac ... done
Successfully installed hvac-0.6.1
(hvac_test) ➜  ~  $ cat ./.venvs/hvac_test/lib/python2.7/site-packages/hvac/version
0.6.1
(hvac_test) ➜  ~  $ pip  install hvac==0.6.0 --no-cache-dir
Collecting hvac==0.6.0
  Downloading https://files.pythonhosted.org/packages/5d/f8/d98dadb05f172b1033e1f0944b4a5e06066370fb13e67008ed15d53216b6/hvac-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: requests>=2.7.0 in ./.venvs/hvac_test/lib/python2.7/site-packages (from hvac==0.6.0) (2.19.1)
Requirement already satisfied: idna<2.8,>=2.5 in ./.venvs/hvac_test/lib/python2.7/site-packages (from requests>=2.7.0->hvac==0.6.0) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in ./.venvs/hvac_test/lib/python2.7/site-packages (from requests>=2.7.0->hvac==0.6.0) (2018.4.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.venvs/hvac_test/lib/python2.7/site-packages (from requests>=2.7.0->hvac==0.6.0) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in ./.venvs/hvac_test/lib/python2.7/site-packages (from requests>=2.7.0->hvac==0.6.0) (1.23)
Installing collected packages: hvac
  Found existing installation: hvac 0.6.1
    Uninstalling hvac-0.6.1:
      Successfully uninstalled hvac-0.6.1
Successfully installed hvac-0.6.0
(hvac_test) ➜  ~  $ cat ./.venvs/hvac_test/lib/python2.7/site-packages/hvac/version
0.6.0
```

As far as the `auth_userpass()` method is concerned, I don't see any changes to that method in particular post-0.5.0: https://github.com/ianunruh/hvac/compare/v0.5.0...v0.6.1. Are you able to share the specific breakage your seeing? I.e., any stack traces or relevant entries from Vault audit logs?

**Comment by jeffwecan** [comment]
So looks like I inadvertently published "hvac-0.6.0-py2.py3-none-any.whl" (seen here: https://pypi.org/project/hvac/0.6.0/#files) when publishing the 0.6.1. So once again thanks for clearly calling that out! 🙏

I'm not the owner of that project on pypi, so I don't believe I have any way of directly removing the offending file. I'll try to get in touch with @ianunruh and see if he can lend a hand there.

**Comment by jeffwecan** [comment]
I also realize now that the breaking change *was* (seemingly) in 0.6.1; its just that rolling back to 0.6.0 left you with the same code as 0.6.1 for the aforementioned publishing mistake. 

With that narrowed down, the two 0.6.1 changes that jump to mind as a potential proximate cause are [GH-149] or [GH-212]. To that end, does your use case involve: A.) calling the `unwrap()`method as part of any response wrapping around a subsequent `auth_userpass()1 call? B.) Does the Vault address in your case have any special nuance (e.g., under some subpath like `company.com/vault`)? Option B seems like a stretch, but option A could conceivably lead to the "missing client token" response you were seeing.

**Comment by jeffwecan** [comment]
The incorrectly published .whl for the 0.6.0 in [pypi](https://pypi.org/project/hvac/0.6.0/#files) should now be resolved at the very least. Once again, my sincere apologies on that front.

**Comment by DGollings** [comment]
Don't worry about the version stuff, it's because I'm using Docker (and had two 'identical' images) that I did think I was going nuts for at least 30 min :). Thanks for fixing it. Can confirm that 0.6.0.post2 works again.

More important is figuring out what broke between 0.6.0 and 0.6.1

slightly pseudocode:
client = hvac.Client(url=hostname:port/v1, verify=False) # (self signed)
client.auth_userpass(user, password)

= Missing client token

I don't do any unwrapping and don't think I do anything special with the vault url. ~Maybe its the /v1?~ No, there's only V1. Tbh I have no idea, had a quick look at the changes and am also pretty surprised I'm hitting this bug. Any spots you'd like me to add debug output to?

**Comment by jeffwecan** [comment]
Ah, I think it is the URL path bit then. `/v1` is implied in all the methods making requests to Vault. Before 0.6.1, that bit would have been silently dropped from the URL provided when instantiating the client. So unless you're adding in an extra `/v1` via some sort of proxy in front of vault, try dropping that part from the url argument and see if that fixes things up?

**Comment by DGollings** [comment]
Can confirm that removing /v1 fixes it. My suggestion would be to either check and throw an exception or silently ignore it again. 

Not that I think many users would add that, not even sure why /v1 was there in the first place. Probably inspired by manually testing endpoints with curl. Thanks for helping me fix it.
