### ISSUE TITLE
Client.is_authenticated() throws Exception when sealed

### ISSUE THREAD

**Issue by kurtismullins** [ianunruh/hvac#22]
Hi,

I'm not really sure if this is a defect or the expected functionality. When I attempt to check whether my client is properly authenticated (to verify my Token) before unsealing the Vault, I get an exception related to the Vault being sealed.

If I call is_authenticated() after unsealing my Vault, it works correctly.

Feel free to close this if it is expected behavior.

Thanks!

**Comment by ianunruh** [comment]
I believe that it's probably better that the error is explicit. Thank you for filing an issue!
