### ISSUE TITLE
Add support for revoke-self endpoint.

### ISSUE THREAD

**Issue by jplabit** [ianunruh/hvac#23]
I'm not sure how you would like this handled, or if you accept pull requests. Figured I would open an issue. Please let me know how you would like this handled going forward. :)

Vault 0.3.0 introduced the capability to revoke your own authentication token as a cleanup step. Reference https://vaultproject.io/docs/http/sys-revoke-self.html

I would like this capability added (maybe a revoke_self_token method?), and also think it would be useful to have an optional parameter to logout to revoke the token. Maybe something like logout(revoke_token=False) by default to not change functionality, but revoke_token=True would call revoke_self_token() before setting self.token = None.

Thanks for putting together this library. Very useful!

**Comment by ianunruh** [comment]
Thanks for reporting this issue. I've added support in 109d72125133889296a80de7e4ce8cc0b552f959
