### ISSUE TITLE
starting connection log should be debug level

### ISSUE THREAD

**Issue by eedgar** [ianunruh/hvac#25]
[INFO    ] Starting new HTTP connection (1): localhost

this should be debug level.  I am using this in another application and it is logging this every time it connects cluttering the output.

**Comment by eedgar** [comment]
import logging
# Suppress the requests module logging.
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.WARNING)

**Comment by ianunruh** [comment]
So, it's generally a bad practice for a library to override the logging for another (dependent) library. That should be left up to the application to decide what logging is important and unimportant.
