### ISSUE TITLE
client.write() returns 204

### ISSUE THREAD

**Issue by frodopwns** [ianunruh/hvac#34]
In vault 0.4.0 I am getting 204 return codes from client.write() instead of 200.

Because of this check: https://github.com/ianunruh/hvac/blob/master/hvac/v1/__init__.py#L35

`None` is returned for both success and failure.

**Comment by ianunruh** [comment]
This is expected behavior. If the write failed, then an exception would be thrown due to a non-200 response code. Returning `None` for `204 No Content` seems reasonable to me.

**Comment by frodopwns** [comment]
What is the point of this then?

```py
 if response.status_code == 200:
            return response.json()
```

**Comment by ianunruh** [comment]
Only some writes return content. For example, a write to the generic secret backend will return nothing and a `204 No Content` status code. But a write to the PKI secret backend to issue a certificate will return JSON about the new certificate and a `200 OK` status code.

It is up to the caller to know if there will be content from the `write` call they make.
