### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by HeathNaylor** [ianunruh/hvac#36]
I have a certificate for a domain but am referencing a local vault server over TLS in my script. I want to ignore the tls verification problem but I get the following error when I do  `assert client.is_authenticated()`

```
SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by ianunruh** [comment]
How are you creating the client? Did you try the `verify=False` flag?

**Comment by HeathNaylor** [comment]
That is better but throws this:

```
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

I can get around this by importing logging and disabling warning capture.

```
import logging
logging.captureWarnings(True)
```

I would not consider this a long term solution. To truly fix this would I need to create my own CA and install the root cert on the system with hvac?

**Comment by ianunruh** [comment]
You can either install the CA certificate on the system or you can set the `verify` flag to the path of the CA certificate, depending on your use case.
