### ISSUE TITLE
!!python/unicode

### ISSUE THREAD

**Issue by HeathNaylor** [ianunruh/hvac#37]
It seems that I am getting python unicode (e.g. u'Some String' ) when I pull data out of  Vault. Is there a way to just have it as a regular ascii string?

**Comment by ianunruh** [comment]
This is from the underlying Requests library that HVAC uses. Could you describe your use case for wanting ASCII instead of Unicode?

**Comment by HeathNaylor** [comment]
I am using python to build a yaml file, the yaml file I build as !!python/unicode in it, I need to have it clean, just the expected text.

**Comment by ianunruh** [comment]
Use safe_dump instead of dump

http://stackoverflow.com/questions/1950306/pyyaml-dumping-without-tags
