### ISSUE TITLE
New release to pip

### ISSUE THREAD

**Issue by mpappas86** [ianunruh/hvac#38]
Hi, I've been using hvac and running into some small issues around new or deprecated options (create-orphan, ttl vs lease) not being supported, but looking at the code here it looks like you've actually got a lot of that fixed and simply haven't sent the next release up yet. Are you planning to do that anytime soon? Would seriously make one guy's life easier. :) Thanks!

**Comment by ianunruh** [comment]
Done!

https://github.com/ianunruh/hvac/releases/tag/v0.2.8

**Comment by ianunruh** [comment]
Actually, I'm having issues doing the push to pypi. I will keep trying, hopefully will get it pushed in the next day.

**Comment by ianunruh** [comment]
The latest version has been built and pushed to PyPI
