### ISSUE TITLE
EC2 Authorization Support

### ISSUE THREAD

**Issue by blarghmatey** [ianunruh/hvac#59]
I was just looking at the changelog for the 0.6.0 release of Vault and noticed the new EC2 auth backend. Is there already work happening to add support for that to hvac? If not I have already started doing some work on that front. I am in the process of introducing Vault into my infrastructure and the EC2 backend will greatly simplify my life.

If there is interest in collaborating on what the end result should look like I am happy to open a PR with what I have so far so that further development can happen more in the open.

**Comment by ianunruh** [comment]
I have not started work on the EC2 auth support, but it's definitely something that will need to be added. Feel free to open a PR, I'm not sure when I'll be able to get to it on my own.

**Comment by blarghmatey** [comment]
I added the work that I have done so far into WIP pull request #61

**Comment by blarghmatey** [comment]
I think the most difficult part of getting that pull request completed is going to be writing a decent test suite, given its dependency on an EC2 environment. Any suggestions or recommendations on that front are welcome.

**Comment by tilgovi** [comment]
It should be possible to mock it. It's possible lyft/metadataproxy could be helpful, even just as inspiration, since it mocks the instance metadata service for non-EC2 environments.

**Comment by ianunruh** [comment]
EC2 support is now available in v0.2.16
