### ISSUE TITLE
Feature request: Automate cubbyhole dance

### ISSUE THREAD

**Issue by zokier** [ianunruh/hvac#71]
Hashicorp has a blogpost detailing how to use cubbyhole backend for authentication with temporary tokens:

https://www.hashicorp.com/blog/vault-cubbyhole-principles.html

While that could be implemented on application side, it'd be great if hvac would have methods that could automate it. The API could be something simple like `client.auth_cubbyhole('TEMP_TOKEN')` which would then fetch the permanent token. I think that would suffice for both the push and pull models described in the blog.

**Comment by otakup0pe** [comment]
We see you @tkinz27 are you going to submit a PR ;)

**Comment by tkinz27** [comment]
already created https://github.com/ianunruh/hvac/pull/119
