### ISSUE TITLE
Interest in a CLI application

### ISSUE THREAD

**Issue by gregdurham** [ianunruh/hvac#73]
Is there any interest from the community in a CLI app utilizing hvac? I have found the cli that the consulate library incredibly useful for interacting with consul, and figured it might be worth adding to this as well.

**Comment by ianunruh** [comment]
Just curious, what would a CLI app based on hvac have to offer over the native Vault CLI client?

**Comment by gregdurham** [comment]
The one thing I have found by using it up to this point is that the output is easier to handle in automation, for instance using the EC2 authentication method, I am only returning the token, which I then pass to a bash variable, rather than using awk/sed to grok the text. That really has been the benefit for us and our application of it. I could imagine that it could simplify other workflows when working with vault, but that would be future use cases. See here for an example: https://github.com/gregdurham/hvac/pull/1

**Comment by TerryHowe** [comment]
Yeh, that is pretty terrible the way the native cli prints the token.  The other thing is any group using python already it would be way easier to convince them to pip install something.

**Comment by gregdurham** [comment]
I am glad I am not the only one that felt that pain, if it is interesting, I will open a PR to this project, I also have a fix for the ec2-auth, there is a bug in master, but outside of that it works well for us in our infrastructure.

**Comment by otakup0pe** [comment]
I'm not sure if it handles your use cases but we've been working on https://github.com/autodesk/aomi (built on hvac) for pulling things out of Vault in vaguely UNIX-y ways.

**Comment by gregdurham** [comment]
Nice! Thanks for sending this over!

**Comment by tilgovi** [comment]
Maybe someone should make a PR to Vault itself to have its CLI optionally print things in a more friendly format? I'm thinking like the way the awscli has --output {text,json,table}

**Comment by csawyerYumaed** [comment]
vault cli includes this already: 
 -format=table           The format for output. By default it is a whitespace-
                          delimited table. This can also be json or yaml.
