### ISSUE TITLE
Feature request: Any plan to support AppRole?

### ISSUE THREAD

**Issue by orontee** [ianunruh/hvac#74]
According to Vault documentation, AppId is now deprecated in favor of AppRole. It would be useful for hvac to support AppRole.

**Comment by jdelic** [comment]
I totally second this request.

**Comment by otakup0pe** [comment]
I've opened a PR with the first pass at this https://github.com/ianunruh/hvac/pull/77 still need to add support for all the little property bits.

**Comment by orontee** [comment]
Thanks. I'll have a look.

**Comment by ianunruh** [comment]
Basic support for AppRole is now available in v0.2.16, thanks to @otakup0pe!
