### ISSUE TITLE
Failed to parse JSON input: invalid character 'U' looking for beginning of value

### ISSUE THREAD

**Issue by webfanatic** [ianunruh/hvac#82]
Any ideas what I'm missing?

Ubuntu 14.04
Python 2.7.6
    hvac==0.2.16
    requests==2.8.1
    pyhcl==0.2.1

Vault v0.6.1

client = hvac.Client(url="http://127.0.0.1:8200", token=self.root_token)
if client.is_authenticated():
    rv = client.write('secret/foo', value='bar')

throwing "hvac.exceptions.InvalidRequest" with error: "u'Failed to parse JSON input: invalid character \\'U\\' looking for beginning of value'"

**Comment by TerryHowe** [comment]
stack trace might help.

The only unknown here is self.root_token, maybe try the token as a string to get rid of that.

**Comment by webfanatic** [comment]
The issue was with the token. I had an embedded newline in the token that caused the issue on the write. Your reply prompted me to look at the token again. I originally didn't think to look at it, as the reads were working fine.
