### ISSUE TITLE
path parameter conflicts with 'path' key

### ISSUE THREAD

**Issue by Albibek** [ianunruh/hvac#98]
When doing write operation on the key containing 'path' field, python gives an error about field conflict.
```
client.write('secret/file', path='/etc/secret/file.secret')
```
Possible solutions:
- give an ability to provide raw json-serializable array throught the additional field
- use less obvious first parameter
- make path a part of keywords

**Comment by otakup0pe** [comment]
Going to track all variants of this woe in #133
